name: Maven Build

on:
  release:
    types: [created]

jobs:
  build_package_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # oldest to newest
      - name: Release hive-1.1.0-hadoop-2.6.5
        run: mvn deploy --batch-mode --update-snapshots -f "hive-client-aio-jdk8.pom" "-Dhive.version=1.1.0" "-Dhadoop.version=2.6.5"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Release hive-1.2.2-hadoop-2.6.5
        run: mvn deploy --batch-mode --update-snapshots -f "hive-client-aio-jdk8.pom" "-Dhive.version=1.2.2" "-Dhadoop.version=2.6.5"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release hive-2.1.1-hadoop-3.0.3
        run: mvn deploy --batch-mode --update-snapshots -f "hive-client-aio-jdk8.pom" "-Dhive.version=2.1.1" "-Dhadoop.version=3.0.3"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}'

      - name: Release hive-2.3.4-hadoop-2.7.7
        run: mvn deploy --batch-mode --update-snapshots -f "hive-client-aio-jdk8.pom" "-Dhive.version=2.3.4" "-Dhadoop.version=2.7.7"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release hive-2.3.7-hadoop-2.9.1
        run: mvn deploy --batch-mode --update-snapshots -f "hive-client-aio-jdk8.pom" "-Dhive.version=2.3.7" "-Dhadoop.version=2.9.1"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release hive-3.1.1-hadoop-3.1.1
        run: mvn deploy --batch-mode --update-snapshots -f "hive-client-aio-jdk8.pom" "-Dhive.version=3.1.1" "-Dhadoop.version=3.1.1"
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bundle artifacts
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging